services:
  vue-app:
    build:
      context: ./vue-app
      dockerfile: Dockerfile
    container_name: vue-app
    ports:
      - '8081:80'
    networks:
      - vue-keycloak-network

networks:
  vue-keycloak-network:
    driver: bridge
